// ============================================================================
// OpenlyContract — pinned V4 constants (generated by tests/test_v4.py, Phase 0)
// ============================================================================
// Drop this into apks/openly as OpenlyContract.java (package com.eurobuddha.openly).
// Registration: runscript parseok + derived-address == ADDR, then
//   newscript trackall:false clean:true script:SCRIPT
// (pandadex DexContract.ensureScript pattern). To read the public board a node
// must first: coinnotify action:add address:ADDR  (a shared address returns 0
// coins until tracked — atomix CommsScanner pattern). trackall:false is
// deliberate: trackall:true would poison `coins relevant:true` with the whole
// board. Ownership of my own bets still surfaces via the state-variable
// relevance scan (my pubkey in ports 0/13).
//
// Verified on-chain 2026-08-04 on two private nodes: 11/11 vectors pass,
// including the security-critical adversarial set (fill cannot rewrite the
// proposition, cannot force refreshcount, cannot under-fund the pot) and
// exact settlement (pot 25 → winner 22.5, loser escrow 2.5, no float brick).
// Single-signature settle export measured at 4861 bytes → fits one comms chunk.

package com.eurobuddha.openly;

public final class OpenlyContract {
    private OpenlyContract() {}

    public static final String ADDR =
        "0xA4A22FD98BE0346547764EB39477CB6FB3E0C6CD22C10BB9D8D590B131B15DE0";
    public static final String ROOT =
        "0x265E914D6805AF4047CD83897AB2CF5E0585D648EE5B407AF1484DC00D39CDA6";

    // Shared comms channel address = hex("OPENLY") — small/rare messages (dispute, notify).
    public static final String MAIL_ADDR = "0x4F50454E4C59";

    // Default arbiter "eurobuddha" — the app author, a known/trusted always-on arbiter offered as a
    // one-tap default on POST. pk→port 2, addr→port 3, commsid→port 11 (enables arbiter chat).
    public static final String EUROBUDDHA_ARB_PK =
        "0x5EC3FDFD44CC6088C503054E0EE2DCEB7DCD6C0E9E20818AB1789F30307CEF72";
    public static final String EUROBUDDHA_ARB_ADDR =
        "0xC6C794C36C0E46E7E4EF681AC2E9E497509A44761BE0858D37E298A16BC81BCF";
    public static final String EUROBUDDHA_ARB_COMMSID =
        "0xa6db2bf249dd706abb9a32f8937df7ca18899390f4cd38af6548c4139103b232d70eca7f5dc2a77043dd83cb8149ca56443b80bc2c96adf5f1a00fd26a912490";

    /**
     * Per-bet SETTLEMENT mailbox: the bet nonce itself (a 32-byte value both parties read from the
     * matched coin's port 9). The heavy signed settlement blob is posted to THIS address, not the
     * shared OPENLY channel — so the counterparty reads `coins address:<settleAddr>` and finds only
     * the 1-2 proposal coins for this bet, scannable at any depth with no shared-address bloat or
     * IPC-limit risk (mirrors PocketFS's per-site addressing). The blob is still sealed to the
     * counterparty's box key, and the nonce is already public on-chain, so using it as an address
     * leaks nothing.
     */
    public static String settleAddr(String nonce) {
        if (nonce == null || nonce.isEmpty()) return MAIL_ADDR;
        return nonce.startsWith("0x") || nonce.startsWith("0X") ? nonce : "0x" + nonce;
    }

    // Main script (clean form, 1177 chars — under the ~1200 KISS limit).
    public static final String SCRIPT =
        "LET ok=PREVSTATE(0) LET oa=PREVSTATE(1) LET ak=PREVSTATE(2) LET aa=PREVSTATE(3) " +
        "LET sd=PREVSTATE(5) LET ws=PREVSTATE(6) LET ph=PREVSTATE(12) " +
        "IF ph EQ 0 THEN " +
        "IF SIGNEDBY(ok) THEN RETURN TRUE ENDIF " +
        "ASSERT SAMESTATE(0 11) ASSERT STATE(12) EQ 1 ASSERT STATE(15) EQ @AMOUNT ASSERT STATE(17) EQ 0 " +
        "ASSERT ak NEQ ok ASSERT ak NEQ STATE(13) " +
        "ASSERT VERIFYOUT(@INPUT @ADDRESS @AMOUNT+ws @TOKENID TRUE) RETURN TRUE ENDIF " +
        "LET ck=PREVSTATE(13) LET ca=PREVSTATE(14) LET os=PREVSTATE(15) LET o=STATE(20) " +
        "IF ph EQ 1 AND SIGNEDBY(ok) AND SIGNEDBY(ck) AND o LTE 1 THEN " +
        "IF o EQ sd THEN LET le=(@AMOUNT-os)/5 " +
        "ASSERT VERIFYOUT(@INPUT oa @AMOUNT-le @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 ca le @TOKENID FALSE) " +
        "ELSE LET le=os/5 " +
        "ASSERT VERIFYOUT(@INPUT ca @AMOUNT-le @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 oa le @TOKENID FALSE) ENDIF " +
        "RETURN TRUE ENDIF " +
        "IF ph EQ 1 AND SIGNEDBY(ak) AND o LTE 1 THEN LET f=@AMOUNT/10 " +
        "IF o EQ sd THEN ASSERT VERIFYOUT(@INPUT oa @AMOUNT-f @TOKENID FALSE) " +
        "ELSE ASSERT VERIFYOUT(@INPUT ca @AMOUNT-f @TOKENID FALSE) ENDIF " +
        "ASSERT VERIFYOUT(@INPUT+1 aa f @TOKENID FALSE) RETURN TRUE ENDIF " +
        "MAST 0x265E914D6805AF4047CD83897AB2CF5E0585D648EE5B407AF1484DC00D39CDA6 RETURN FALSE";

    // MAST leaf scripts + their proofs (from mmrcreate; order = refresh, timeout, void).
    public static final String LEAF_REFRESH =
        "LET ok=PREVSTATE(0) LET ck=PREVSTATE(13) " +
        "IF PREVSTATE(12) EQ 1 AND (SIGNEDBY(ok) OR SIGNEDBY(ck)) THEN " +
        "ASSERT SAMESTATE(0 16) ASSERT STATE(17) EQ PREVSTATE(17)+1 ASSERT PREVSTATE(17) LT 200 " +
        "ASSERT VERIFYOUT(@INPUT @ADDRESS @AMOUNT @TOKENID TRUE) RETURN TRUE ENDIF RETURN FALSE";
    public static final String PROOF_REFRESH =
        "0x00010000010200000000205D9A5EB9E9B5B81F501B908C3ADEF658BF3332A0C81A18551F3DD94AA61EC46100010000000000204952F29FD94AAD7098C335B7798D19B5F9A352441DAF25F14BC509EAA9FCA435000100";

    public static final String LEAF_TIMEOUT =
        "LET oa=PREVSTATE(1) LET ca=PREVSTATE(14) LET os=PREVSTATE(15) " +
        "IF PREVSTATE(12) EQ 1 AND @COINAGE GT PREVSTATE(4) THEN " +
        "ASSERT VERIFYOUT(@INPUT oa os @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 ca @AMOUNT-os @TOKENID FALSE) " +
        "RETURN TRUE ENDIF RETURN FALSE";
    public static final String PROOF_TIMEOUT =
        "0x00010000010201000000203A5ED927C3496D3D2384ECFB29E753FF36B22BD58A71FC9F3C1D62AAA3D1C48500010000000000204952F29FD94AAD7098C335B7798D19B5F9A352441DAF25F14BC509EAA9FCA435000100";

    public static final String LEAF_VOID =
        "LET ok=PREVSTATE(0) LET oa=PREVSTATE(1) LET ck=PREVSTATE(13) LET ca=PREVSTATE(14) LET os=PREVSTATE(15) " +
        "IF PREVSTATE(12) EQ 1 AND SIGNEDBY(ok) AND SIGNEDBY(ck) AND STATE(20) EQ 2 THEN " +
        "ASSERT VERIFYOUT(@INPUT oa os @TOKENID FALSE) ASSERT VERIFYOUT(@INPUT+1 ca @AMOUNT-os @TOKENID FALSE) " +
        "RETURN TRUE ENDIF RETURN FALSE";
    public static final String PROOF_VOID =
        "0x00010000010101000000200EDABE3FB02ACE97CF1A74A6451A52EAB463DB947C585EAC86DCD99789F30CAE000100";

    // Measured Phase 0: single-signature settle txnexport = 4861 bytes → one 8 KB chunk.
    public static final int SETTLE_EXPORT_BYTES = 4861;
}
